# Generated by Django 5.1.2 on 2024-10-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_stock_stock_product_product_total_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_stock',
        ),
    ]
